### ISSUE TITLE
upgrade ACE

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#642]
ACE doesn't build on Ubuntu 20.04
```
In file included from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/OS_NS_stropts.h:30,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/OS_NS_sys_socket.h:28,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/ACE.inl:5,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/ACE.h:887,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/ACE.cpp:1:
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/os_include/os_stropts.h:56:17: fatal error: stropts.h: No such file or directory
```
https://github.com/SyneRBI/SIRF-SuperBuild/runs/4894731269?check_suite_focus=true#step:7:3604

our ACE version is out-of-date: https://stackoverflow.com/questions/61661076/ace-library-in-ubuntu-20-04

_Originally posted by @KrisThielemans in https://github.com/SyneRBI/SIRF-SuperBuild/issues/413#issuecomment-1018369166_

**Comment by KrisThielemans** [comment]
Version is currently hardwired in https://github.com/paskino/libace-conda/blob/0f0db1fa5841560e2c8bdf790deaa9d79093e48e/CMakeLists.txt#L25

Our `version_config.cmake` points to most recent version of the repo https://github.com/SyneRBI/SIRF-SuperBuild/blob/885c4c2cf70eeccb98e79ae768192323a97457b5/version_config.cmake#L183-L184

Aside from upgrading it, I think we should tag libace-conda accordingly

**Comment by paskino** [comment]
Does it need upgrading to ACE 6.5.9?

**Comment by KrisThielemans** [comment]
yes, or later I guess

**Comment by paskino** [comment]
closed by #656

**Comment by KrisThielemans** [comment]
Re-opening.
Actually
https://github.com/paskino/libace-conda/tree/ACE_version_6.5.9/ is using 6.4.7...
https://github.com/paskino/libace-conda/blob/0f0db1fa5841560e2c8bdf790deaa9d79093e48e/CMakeLists.txt#L25
https://github.com/paskino/libace-conda/blob/0f0db1fa5841560e2c8bdf790deaa9d79093e48e/CMakeLists.txt#L42

**Comment by KrisThielemans** [comment]
@paskino this still need fixing.
could use a more recent version of ACE while you're doing that, but as you prefer.

**Comment by paskino** [comment]
I think this can be closed as of https://github.com/paskino/libace-conda/tree/v6.5.9 and #663 ?

**Comment by KrisThielemans** [comment]
indeed
