### ISSUE TITLE
need to upgrade boost for ISMRMRD 1.5?

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#643]
we're now in ISMRMRD 1.5.0 but it fails to compile with our default boost 1.65.1.
https://github.com/SyneRBI/SIRF-SuperBuild/runs/4894972076?check_suite_focus=true#step:7:24959
```
                  from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/ISMRMRD/utilities/generate_cartesian_shepp_logan.cpp:18:
/home/runner/install/include/boost/mpl/assert.hpp:188:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
```
This is rather weird though as it works fine with the system boost on Ubuntu 18.04 which is 1.65.1 (and is tested for instance https://github.com/SyneRBI/SIRF-SuperBuild/runs/4894972352?check_suite_focus=true#step:6:105)

**Comment by KrisThielemans** [comment]
> This is rather weird though as it works fine with the system boost on Ubuntu 18.04 

could be because gcc 9 issues a warning and gcc 8 doesn't.

**Comment by KrisThielemans** [comment]
@paskino I think you've done this in #438. Backport to `master`? (there's some other updates there which I guess we can just as well do)

**Comment by KrisThielemans** [comment]
by the way, still compilations warnings (and hence errors with their settings) with Boost 1.71.0 when boost::test is installed

**Comment by paskino** [comment]
closed by #651
