### ISSUE TITLE
our current version of XROOTD fails to compile on Ubuntu 22.04

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#782]
Error is
```
..../builds/ROOT/build/XROOTD-prefix/src/XROOTD/src/XrdCrypto/XrdCryptosslgsiAux.cc:901:32: error: invalid conversion from ‘const rsa_st*’ to ‘RSA*’ {aka ‘rsa_st*’} [-fpermissive]
```
This is a known problem with openssl 3.0, see e.g. [here](https://bugs.gentoo.org/806388) and fixed at https://github.com/xrootd/xrootd/pull/1517.

Probably best to upgrade our ROOT version to [v6-26-10](https://github.com/root-project/root/releases/tag/v6-26-10)
