### ISSUE TITLE
Nose is unmaintained and no longer works with Python 3.10

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#646]
Errors
```
  File "/home/kthielem/.local/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```
This won't be fixed https://github.com/nose-devs/nose/issues/1099

That issue mentions some solutions
- move to `nose2`
- move to `pytest` (used by STIR by the way)
- ```
   $ pip uninstall -y nose
   $ pip install -U nose --no-binary :al
  ```
- ```
   $ pip uninstall -y nose
   $ pip install nose-py3
```
I've tried the latter (on CentOS) and it worked.

I don't know if `nose-py3` is maintained and good to use long-term.

@casperdcl any suggestions?

**Comment by KrisThielemans** [comment]
I've created the issue here as the workaround can be implemented in docker and the VM, but longer term changes will have to be in SIRF

**Comment by casperdcl** [comment]
I've migrated to `pytest` many moons ago :shrug:

**Comment by KrisThielemans** [comment]
The above work-around of using `nose-py3`  doesn't work on Ubuntu 22.04, Python 3.10.6
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/__main__.py", line 8, in <module>
    run_exit()
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/core.py", line 117, in __init__
    unittest.TestProgram.__init__(
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/core.py", line 144, in parseArgs
    self.config.configure(argv, doc=self. Usage())
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/config.py", line 351, in configure
    self.plugins.configure(options, self)
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/plugins/manager.py", line 279, in configure
    cfg(options, config)
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/plugins/manager.py", line 93, in __call__
    return self. Call(*arg, **kw)
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/plugins/manager.py", line 161, in simple
    result = meth(*arg, **kw)
  File "/home/sirfuser/.local/lib/python3.10/site-packages/nose/plugins/cover.py", line 168, in configure
    self.skipModules = sys.modules.keys()[:]
TypeError: 'dict_keys' object is not subscriptable

```

**Comment by KrisThielemans** [comment]
affected tests
```
	  2 - MR_TESTS_PYTHON (Failed)
	  7 - REG_TESTS_PYTHON (Failed)
	 11 - PET_TESTS_PYTHON (Failed)
```
